[package]
name = "to_df"
version.workspace = true
edition.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
serde_json = { workspace = true }
polars = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
dive = { path = "../dive" }
